stages:
  - test
  - deploy

image: node:latest

cache:
  paths:
    - node_modules

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

pages:
  stage: deploy
  script:
    - npm install
    - npm run build:sass
    - npm run build:eleventy
    # install minifiers
    - npm install html-minifier css-minify uglify-js -g
    # minify js
    - uglifyjs public/js/script.js -o public/js/script.js -c -m
    # minify html
    - html-minifier --input-dir public --output-dir public --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js --file-ext html
    # minify css
    - css-minify -d public/css
  artifacts:
    paths:
      - public
  only:
    - main
